version: '2'
services:
    rt:
        build: .
        ports:
            - '443'
        links:
            - mysql
        volumes:
            - ./testing/secrets:/opt/share/secrets/rt:ro

    mysql:
        build:
            context: testing
            dockerfile: mysql.Dockerfile

    itest:
        build:
            context: testing
            dockerfile: itest.Dockerfile
